apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: training-orchestrator-role
  namespace: training
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: training-orchestrator-binding
  namespace: training
subjects:
- kind: ServiceAccount
  name: training-orchestrator
  namespace: training
roleRef:
  kind: Role
  name: training-orchestrator-role
  apiGroup: rbac.authorization.k8s.io
